### ISSUE TITLE
Urban datasets

### ISSUE THREAD

**Issue by morsingher** [fdarmon/wild_deep_mvs#1]
Hi, thank you for sharing both the paper and the code. I'm working on something similar, so I was very happy to read your results. 

I would like to ask if you ever considered urban datasets in your evaluation, especially multi-camera datasets such as [nuScenes](https://www.nuscenes.org/) or [DDAD](https://github.com/TRI-ML/DDAD). I'm asking this for two main reasons:

1. Internet data are surely "in the wild", but they mostly focus on a single giant object (i.e. a building) in the image, for which a lot of diverse views can be captured. On the other hand, urban data have no clear subject, a lot of dynamic objects and several textureless areas to deal with, which is definitely an even harder test for MVS networks. 
2. MVS networks cannot be trained in a supervised way on urban data, therefore your insights on unsupervised methods might be interesting to be validated also on these kind of data. 

What are your thoughts on this?

**Comment by fdarmon** [comment]
Hi, sorry for the late reply and thank you for your interest in our work

It is a good idea to try evaluating on urban datasets. I think MVS networks need to be evaluated on more various datasets than the usual ones and urban datasets clearly have challenges of their own. Another suggestion that was made to me is to evaluate on indoor datasets like eth3d. 

It would surely make the evaluation stronger but I have moved to another research subject at the moment. Feel free to use the code with such datasets or even make a pull request. 

It could be nice to try unsupervised learning on such data as well. Maybe the dynamic objects will be masked out directly with the "occlusion mask" of current code since they will not have a consistent depth across multiple views. You may have a problem with accuracy in textureless area but I don't think it will disturb the training.
